name: Python Application Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  contents: write  # This permission allows the workflow to push code
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Heroku Login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku auth:token

    - name: Add Heroku git remote
      env:
        HEROKU_APP_NAME: almao1a
      run: heroku git:remote -a $HEROKU_APP_NAME

    - name: List Git remotes
      run: git remote -v
    
    - name: Deploy to Heroku
      run: |
        git fetch --unshallow
        git config --global user.email "nikhilreddyp29@gmail.com"
        git config --global user.name "Nikhil Reddy"
        git push origin HEAD:main
